#!/usr/bin/python
#-*-coding:utf-8 -*-

"""
Django settings for bookmarks project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS as TCP
# Build paths inside the project like this:os.path.join(BASE_DIR, ...)
import os
import logging

BASE_DIR = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING:keep the secret key used in production secret!
SECRET_KEY = '-ocvjf&p1d%!))e)dpp_uu39s-+=)w&!*oc$vl48o@n*_1fh%2'

# SECURITY WARNING:don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'suit',
    'account',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'social.apps.django_app.default',
    # 'sorl.thumbnail',
    # 'bootstrap3',
    # 'django_admin_bootstrapped',
    'django.contrib.admin',
	
	# 用xadmin替换admin，在后台管理系统提供更好看的样式
    # 'xadmin',
    # 'crispy_forms',
    # 'reversion',  #  需要pip install django-reversion
    # 'silk'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfResponseMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    
    # 'silk.middleware.SilkyMiddleware',
)

ROOT_URLCONF = 'bookmarks.urls'

TEMPLATE = [
    {
        'BACKEND':'django.template.backends.django.DjangoTemplates',
        'DIRS':[],
        'APP_DIRS':True,
        'OPTIONS':{
            'context_processors':[
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'bookmarks.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default':{
        'ENGINE':'django.db.backends.sqlite3',
        'NAME':os.path.join(BASE_DIR, 'db.sqlite3'),
        #'ENGINE': 'django.db.backends.mysql',
        #'NAME': 'radarsys',
        #'USER': 'root',
        #'PASSWORD': 'admin',
        #'HOST': '192.168.60.27',
        #'PORT': '3306',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = False
USE_TZ = False

DATETIME_FORMAT = 'Y-m-d H:i:s' 
DATE_FORMAT = 'Y-m-d'


TEMPLATE_CONTEXT_PROCESSORS = TCP + ('django.core.context_processors.request',)

SUIT_CONFIG = {
    'ADMIN_NAME': '雷盾防护管理系统',
    # 'MENU': (
        # 'sites',
        # {'app': 'account', 'label': '账户管理', 'icon': 'icon-chevron-right'},
        # {'app': 'actions', 'label': '操作日志', 'icon': 'icon-chevron-right'},
        # {'label': '认证和授权', 'icon': 'icon-lock'},		
    # ),
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder"
)


from django.core.urlresolvers import reverse_lazy

LOGIN_REDIRECT_URL = reverse_lazy('dashboard')
LOGIN_URL = reverse_lazy('login')
LOGOUT_URL = reverse_lazy('logout')

ABSOLUTE_URL_OVERRIDES = {
    'auth.user':lambda u:reverse_lazy('user_detail', args=[u.username])
}

#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_HOST_USER = 'my_account@gmail.com'
#EMAIL_HOST_PASSWORD = ''
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True

# python-social-auth settings
AUTHENTICATION_BACKENDS = (
    # 'social.backends.facebook.Facebook2OAuth2',
    # 'social.backends.google.GoogleOAuth2',
    # 'social.backends.twitter.TwitterOAuth',

    'django.contrib.auth.backends.ModelBackend',
    'account.authentication.EmailAuthBackend',
)

SOCIAL_AUTH_FACEBOOK_KEY = ''
SOCIAL_AUTH_FACEBOOK_SECRET = ''

SOCIAL_AUTH_TWITTER_KEY = ''
SOCIAL_AUTH_TWITTER_SECRET = ''

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = ''
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = ''


REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0

CACHES = {
    'default':{
        'BACKEND':'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION':'/var/tmp/django_cache',
        'TIMEOUT':600,
        'OPTIONS':{
            'MAX_ENTRIES':1000
        }
    }
}

logging.basicConfig(
level = logging.DEBUG,
format ='%(asctime)s %(levelname)s %(message)s',
filename ='./myapp.log',
filemode ='w'
)

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = True 
EMAIL_USE_SSL = True 
EMAIL_HOST = 'smtp.qq.com' 
EMAIL_PORT = 465
EMAIL_HOST_USER = '1044825525@qq.com'
EMAIL_HOST_PASSWORD = 'shlvewmsheooebhd'
EMAIL_HOST_PASSWORD = 'myuchfmmdspubbga'  # 密码
# EMAIL_HOST_PASSWORD = 'myuchfmmdspubbga'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

